config setup
    charondebug="ike 2, knl 2, cfg 2"
    uniqueids=no

conn test-conn
    auto=add
    type=tunnel
    keyexchange=ikev1
    authby=secret
    left=192.168.50.11
    leftid=@right
    leftsubnet=192.168.50.11/32
    right=192.168.50.10
    rightid=@left
    rightsubnet=192.168.50.10/32
    ike=aes256-sha256-modp1024!
    esp=aes256-sha256!
    ikelifetime=60m
    lifetime=60m
