name: sih2026

services:
  vpn-left:
    build: ./strongswan
    container_name: vpn-left
    hostname: vpn-left
    cap_add:
      - NET_ADMIN
    networks:
      vpnnet:
        ipv4_address: 192.168.50.10
    volumes:
     - ./captures:/captures
     # - ./config/left.conf:/etc/ipsec.conf:ro
     - ./config/ipsec.secrets:/etc/ipsec.secrets.template:ro
    command: >
      bash -c "cp /etc/ipsec.secrets.template /etc/ipsec.secrets &&
               chmod 600 /etc/ipsec.secrets &&
               ipsec start &&
               sleep infinity"

  vpn-right:
    build: ./strongswan
    container_name: vpn-right
    hostname: vpn-right
    cap_add:
      - NET_ADMIN
    networks:
      vpnnet:
        ipv4_address: 192.168.50.11
    volumes:
      - ./captures:/captures
      #- ./config/right.conf:/etc/ipsec.conf:ro
      - ./config/ipsec.secrets:/etc/ipsec.secrets.template:ro
    command: >
      bash -c "cp /etc/ipsec.secrets.template /etc/ipsec.secrets &&
               chmod 600 /etc/ipsec.secrets &&
               ipsec start &&
               sleep infinity"

networks:
  vpnnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24