config setup
    charondebug="ike 2, knl 2, cfg 2"

conn test-conn
    keyexchange=ikev2
    authby=secret
    left=192.168.50.10
    leftid=@left
    right=192.168.50.11
    rightid=@right
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    auto=add
    forceencaps=yes
